#!/usr/bin/env python3
"""Installation script for SSH"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'script'))
from helpers import (
    dry,
    get_machine_config,
    info,
    install_symlinks,
    is_dry_run,
    parse_dry_run,
    success,
    write_file,
)


def generate_claude_askpass():
    """Generate an SSH_ASKPASS helper that fetches the claude signing
    key passphrase from 1Password.

    On shells where ``ssh.claudeSigningKeyPasswordRef`` is configured,
    ``ssh/ssh.sh`` invokes this helper to add the claude signing key
    to ssh-agent without an interactive prompt. Calling ``op read``
    also unlocks 1Password biometric for the session, so the first
    op-ssh-sign-backed git commit afterwards doesn't have to.
    """
    home = Path.home()
    xdg_config_home = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
    askpass = xdg_config_home / 'dotfiles' / 'ssh-askpass-claude.sh'

    machine_config, _ = get_machine_config()
    pw_ref = machine_config.get('ssh', {}).get('claudeSigningKeyPasswordRef')

    if not pw_ref:
        if askpass.exists():
            if is_dry_run():
                dry(f"would remove stale {askpass}")
            else:
                askpass.unlink()
                info(f"Removed stale {askpass}")
        return

    content = (
        '#!/bin/sh\n'
        '# Generated by ssh/install.py — do not edit by hand\n'
        '# SSH_ASKPASS helper: prints the claude signing key passphrase.\n'
        f'exec op read {pw_ref!r}\n'
    )

    if askpass.exists() and askpass.read_text() == content:
        success("SSH askpass helper already up to date")
        return

    write_file(askpass, content, mode=0o700)
    success(f"Generated {askpass}")


def main():
    parse_dry_run()
    install_symlinks(Path(__file__).resolve().parent)

    info("Configuring SSH...")

    ssh_dir = Path.home() / '.ssh'
    if is_dry_run():
        dry(f"would ensure {ssh_dir} exists with mode 0700 and config.local exists")
    else:
        ssh_dir.mkdir(mode=0o700, exist_ok=True)

        # Ensure correct permissions
        current_mode = ssh_dir.stat().st_mode & 0o777
        if current_mode != 0o700:
            ssh_dir.chmod(0o700)
            info(f"Fixed ~/.ssh permissions: {oct(current_mode)} -> 0700")

        # Create empty config.local if it doesn't exist
        config_local = ssh_dir / 'config.local'
        if not config_local.exists():
            config_local.touch(mode=0o600)
            info("Created ~/.ssh/config.local")

    generate_claude_askpass()

    success("SSH configured")
    return 0


if __name__ == '__main__':
    sys.exit(main())
