#!/usr/bin/env python3
"""Installation script for Git"""

import os
import socket
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'script'))
from helpers import info, success, error, brew_install, brew_is_installed


# Machine-specific git user settings
# Default is used for machines not explicitly listed
MACHINE_CONFIGS = {
    'default': {
        'name': 'Leo Simons',
        'email': 'mail@leosimons.com',
    },
    'sbp-mac-ai.local': {
        'name': 'Leo-Bot Simons',
        'email': 'bot@leosimons.com',
    },
}


def get_git_user_config():
    """Get git user config for current machine"""
    hostname = socket.gethostname()
    if hostname in MACHINE_CONFIGS:
        return MACHINE_CONFIGS[hostname], hostname
    return MACHINE_CONFIGS['default'], hostname


def generate_local_config():
    """Generate machine-specific git config.local"""
    home = Path.home()
    xdg_config_home = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
    config_local = xdg_config_home / 'git' / 'config.local'

    config, hostname = get_git_user_config()

    content = f"""# Machine-specific git configuration
# Generated by git/install.py for hostname: {hostname}

[user]
    name = {config['name']}
    email = {config['email']}
"""

    # Ensure directory exists
    config_local.parent.mkdir(parents=True, exist_ok=True)

    # Check if content changed
    if config_local.exists():
        existing = config_local.read_text()
        if existing == content:
            success(f"Git config.local already up to date ({config['name']})")
            return True

    config_local.write_text(content)
    success(f"Generated git config.local for {hostname}: {config['name']} <{config['email']}>")
    return True


def main():
    info("Installing Git...")

    if brew_is_installed('git'):
        success("Git already installed")
    elif brew_install('git'):
        success("Git installed")
    else:
        error("Failed to install Git")
        return 1

    generate_local_config()
    return 0


if __name__ == '__main__':
    sys.exit(main())
