#!/usr/bin/env python3
"""Installation script for shared coding-agent skills.

Installs the skills.sh CLI and every skill declared in `skills.txt` into
the shared `agents/skills/` directory, which the per-agent topics
(claude, codex, copilot, gemini, opencode, pi-coding-agent) link into
their own configuration directories.
"""

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    SKILLS_DIR,
    XDG_CONFIG_HOME,
    command_exists,
    dry,
    error,
    info,
    is_dry_run,
    link_directory,
    load_skills_manifest,
    npm_install_global,
    parse_dry_run,
    run_cmd,
    success,
    warn,
    write_file,
)

# skills.sh installs into one directory per agent. Ask for claude-code's
# layout (`<project>/.claude/skills/<skill>`) in a staging directory and
# move the result into the shared skills directory ourselves, so the
# install does not depend on which agent topics ran first.
STAGING_AGENT = "claude-code"

# Agents without a dedicated topic (Zed, Cursor, Cline, Warp, Amp, ...)
# read skills from these shared locations instead of an agent-specific
# directory.
UNIVERSAL_SKILL_DIRS = (
    Path.home() / ".agents" / "skills",
    XDG_CONFIG_HOME / "agents" / "skills",
)

GITIGNORE_HEADER = """\
# Generated by agents/install.py from agents/skills.txt.
# Skills fetched from skills.sh are installed here but not vendored.
"""


def skills_command():
    """Return the argv prefix for the skills.sh CLI."""
    if command_exists("skills"):
        return ["skills"]
    return ["npx", "-y", "skills"]


def install_cli():
    """Install the skills.sh CLI globally so `skills` is on PATH."""
    if command_exists("skills"):
        success("skills CLI already installed")
        return True

    info("Installing the skills.sh CLI...")
    if npm_install_global("skills"):
        success("skills CLI installed")
        return True

    warn("Failed to install the skills CLI; falling back to `npx skills`")
    return False


def install_agent_browser():
    """Install the CLI that the agent-browser skill drives.

    The skill itself is a discovery stub: it shells out to `agent-browser`,
    which serves version-matched instructions and drives its own Chrome
    build. npm blocks the package's postinstall script by default, so fetch
    the browser explicitly.
    """
    if command_exists("agent-browser"):
        success("agent-browser already installed")
    else:
        info("Installing agent-browser...")
        if not npm_install_global("agent-browser"):
            warn("Failed to install agent-browser; its skill will not work")
            return
        success("agent-browser installed")

    if run_cmd(["agent-browser", "install"], check=False).returncode != 0:
        warn("`agent-browser install` failed; run it by hand to fetch Chrome")


def write_gitignore(entries):
    """Regenerate agents/skills/.gitignore from the manifest."""
    lines = [GITIGNORE_HEADER]
    lines += [f"{name}/" for _repo, name in sorted(entries, key=lambda e: e[1])]
    content = "\n".join(lines) + "\n"

    gitignore = SKILLS_DIR / ".gitignore"
    if gitignore.exists() and gitignore.read_text() == content:
        return
    write_file(gitignore, content)
    success(f"Wrote: {gitignore}")


def fetch_skill(repository, name, staging):
    """Fetch one skill into the staging directory and move it into place."""
    result = run_cmd(
        [
            *skills_command(),
            "add",
            repository,
            "--skill",
            name,
            "--agent",
            STAGING_AGENT,
            "--copy",
            "--yes",
        ],
        check=False,
        cwd=staging,
    )
    if result.returncode != 0:
        error(f"Failed to install skill '{name}' from {repository}")
        return False

    fetched = staging / ".claude" / "skills" / name
    if not fetched.is_dir():
        error(f"skills CLI did not produce {fetched}")
        return False

    destination = SKILLS_DIR / name
    if destination.exists():
        shutil.rmtree(destination)
    shutil.move(str(fetched), str(destination))
    success(f"Installed skill: {destination}")
    return True


def install_skills(update):
    """Install every skill declared in skills.txt. Returns True on success."""
    entries = load_skills_manifest()
    write_gitignore(entries)

    if any(name == "agent-browser" for _repository, name in entries):
        install_agent_browser()

    pending = []
    for repository, name in entries:
        if (SKILLS_DIR / name).is_dir() and not update:
            success(f"Skill already installed: {name}")
        else:
            pending.append((repository, name))

    if not pending:
        return True

    if is_dry_run():
        for repository, name in pending:
            dry(f"would install skill '{name}' from {repository} into {SKILLS_DIR}")
        return True

    ok = True
    with tempfile.TemporaryDirectory(prefix="dotfiles-skills-") as tmpdir:
        staging = Path(tmpdir)
        for repository, name in pending:
            info(f"Installing skill '{name}' from {repository}...")
            ok = fetch_skill(repository, name, staging) and ok
    return ok


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="preview without changing anything"
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="re-fetch skills that are already installed",
    )
    args = parser.parse_args()
    parse_dry_run()

    info("Setting up shared coding-agent skills...")

    for skills_dir in UNIVERSAL_SKILL_DIRS:
        link_directory(SKILLS_DIR, skills_dir)

    install_cli()

    return 0 if install_skills(args.update) else 1


if __name__ == "__main__":
    sys.exit(main())
